<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>autoware_image_ego_mask</name>
  <version>0.0.0</version>
  <description>Static 2D polygon masking for ego-vehicle regions in camera images.</description>

  <maintainer email="dev@tier4.jp">TIER IV</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>
  <depend>image_transport</depend>
  <depend>cv_bridge</depend>
  <depend>yaml-cpp</depend>
  <!-- <depend>OpenCV</depend> -->

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

